development:
  name: "development"
  baseUrl: "http://664-vuld.fplay.io"
  backendUrl: "http://664-vuld.fplay.io:4031"

production:
  name: "production"
#  baseUrl: "http://bp.magsto.com"
  baseUrl: "http://665-vuff.magsto.com"
  backendUrl: "http://665-vuff.magsto.com:4031"
#  baseUrl: "http://localhost:4030"
