development:
  name: "development"
  baseUrl: "http://localhost"

production:
  name: "production"
#  baseUrl: "http://bp.magsto.com"
  baseUrl: "http://664-vuto.magsto.com"
#  baseUrl: "http://localhost:4030"
